<option value="Python">Python</option>
<option value="Datascience">Datascience</option>
<option value="Machine learning">Machine learning</option>
<option value="Aws">Aws</option>
<option value="Azure">Azure</option>
<option value="Salesforce">Salesforce</option>
<option value="Hadoop">Hadoop</option>
<option value="Linux">Linux</option>
<option value="Java">Java</option>
<option value="C">C</option>
<option value="C++">C++</option>
<option value="Android">Android</option>
<option value="Iot">Iot</option>
<option value="Ios">Ios</option>
<option value="Sap">Sap</option>
<option value="ORACLE">ORACLE</option>
<option value="Data science with R">Data science with R</option>
<option value="Power bi">Power bi</option>
<option value="Tableau">Tableau</option>
<option value="Ms SQL">Ms SQL</option>
<option value="SQL">SQL</option>
<option value="Mis">Mis</option>
<option value="AutoCAD">AutoCAD</option>
<option value="Embedded system">Embedded system</option>
<option value="Plc scada">Plc scada</option>
<option value="Php">Php</option>
<option value="Web designing">Web designing</option>
<option value="UI">UI</option>
<option value="React">React</option>
<option value="Mern">Mern</option>
<option value="Angular">Angular</option>
<option value="Mean">Mean</option>
<option value="Graphic design">Graphic design</option>
<option value="Dotnet">Dotnet</option>
<option value="Testing">Testing</option>
<option value="Ccna">Ccna</option>
<option value="Ccnp">Ccnp</option>
<option value="MCSa">MCSa</option>
<option value="Digital Marketing">Digital Marketing</option>
<option value="Ethical hacking">Ethical hacking</option>
<option value="German Language">German Language</option>
<option value="Other">Other</option>